- hosts: "{{ h }}"

  vars_files:
    # secrets.yml must define gitlab_private_roken
    - secrets.yml

  roles:
    # git clone https://git.forgeservicelab.fi/ansible-roles/forge_hostname.git
    - role: forge_hostname
    # git clone https://git.forgeservicelab.fi/ansible-roles/forge_ssl.git
    - role: forge_ssl
    # git clone https://git.forgeservicelab.fi/ansible-roles/forge_users.git
    - role: forge_users
      forge_users_private_token: gitlab_private_token
      forge_users_list:
        - jrodrigu
        - tkarasek
        - pkivikan
        - akoskine
    # git clone https://git.forgeservicelab.fi/ansible-roles/jenkins.git
    - role: jenkins
      jenkins_plugins: [ldap]
      jenkins_nginx_proxy: yes
      jenkins_nginx_hostname: "{{ ansible_fqdn }}"
      tags: app

