# forge_ssl
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_ssl.git
  path: roles/

# forge_users
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_users.git
  path: roles/

# jenkins
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/jenkins.git
  path: roles/

# timezone
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/timezone.git
  path: roles/

# forge_jenkins_mods
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_jenkins_mods.git
  path: roles/
